// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1beta1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/wangpy1489/DNative/pkg/apis/batch/v1beta1.BatchJob":       schema_pkg_apis_batch_v1beta1_BatchJob(ref),
		"github.com/wangpy1489/DNative/pkg/apis/batch/v1beta1.BatchJobSpec":   schema_pkg_apis_batch_v1beta1_BatchJobSpec(ref),
		"github.com/wangpy1489/DNative/pkg/apis/batch/v1beta1.BatchJobStatus": schema_pkg_apis_batch_v1beta1_BatchJobStatus(ref),
	}
}

func schema_pkg_apis_batch_v1beta1_BatchJob(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BatchJob is the Schema for the batchjobs API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/wangpy1489/DNative/pkg/apis/batch/v1beta1.BatchJobSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/wangpy1489/DNative/pkg/apis/batch/v1beta1.BatchJobStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/wangpy1489/DNative/pkg/apis/batch/v1beta1.BatchJobSpec", "github.com/wangpy1489/DNative/pkg/apis/batch/v1beta1.BatchJobStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_batch_v1beta1_BatchJobSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BatchJobSpec defines the desired state of BatchJob",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_batch_v1beta1_BatchJobStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BatchJobStatus defines the observed state of BatchJob",
				Type:        []string{"object"},
			},
		},
	}
}
