apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httptriggers.batch.k8s.io
spec:
  group: batch.k8s.io
  names:
    kind: HttpTrigger
    listKind: HttpTriggerList
    plural: httptriggers
    singular: httptrigger
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HttpTrigger is the Schema for the httptriggers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HttpTriggerSpec defines the desired state of HttpTrigger
          properties:
            jobref:
              properties:
                name:
                  type: string
              required:
              - name
              type: object
            relativeurl:
              type: string
          required:
          - jobref
          - relativeurl
          type: object
        status:
          description: HttpTriggerStatus defines the observed state of HttpTrigger
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
