apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: batchtemplates.batch.k8s.io
spec:
  group: batch.k8s.io
  names:
    kind: BatchTemplate
    listKind: BatchTemplateList
    plural: batchtemplates
    singular: batchtemplate
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BatchTemplate is the Schema for the batchtemplates API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BatchTemplateSpec defines the desired state of BatchTemplate
          properties:
            storageInfo:
              properties:
                mountPath:
                  type: string
                storageName:
                  type: string
              required:
              - mountPath
              - storageName
              type: object
            template:
              type: object
            type:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - storageInfo
          - template
          - type
          type: object
        status:
          description: BatchTemplateStatus defines the observed state of BatchTemplate
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
