apiVersion: apps/v1
kind: Deployment
metadata:
  name: DNative
spec:
  replicas: 1
  selector:
    matchLabels:
      name: DNative
  template:
    metadata:
      labels:
        name: DNative
    spec:
      serviceAccountName: DNative
      containers:
        - name: DNative
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - DNative
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "DNative"
